tango_with_django_project/rango/urls.py
from django.urls import path 
from rango import views
app_name = 'rango'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('add_category/', views.add_category, name = 'add_category'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
]

tango_with_django_project/tango_with_django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    #The above maps any URLs starting with rango/ to be handled by rango. path('admin/', admin.site.urls),
    path('admin/', admin.site.urls),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.text import slugify

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default = 0)
    likes = models.IntegerField(default = 0)
    slug = models.SlugField(unique=True)
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name) 
        super(Category, self).save(*args, **kwargs)
    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.title

tango_with_django_project/rango/forms.py
from django import forms
from rango.models import Page, Category
from django.contrib.auth.models import User 
from rango.models import UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField( max_length = 128, help_text = "Please enter the category name." )
    views = forms.IntegerField( widget = forms.HiddenInput(), initial = 0 )
    likes = forms.IntegerField( widget = forms.HiddenInput(), initial = 0 )
    slug = forms.CharField( widget = forms.HiddenInput(), required = False )

    # An inline class to provide additional information on the form.
    class Meta:
    # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField( max_length= 128, help_text = "Please enter the title of the page." )
    url = forms.URLField( max_length = 200, help_text = "Please enter the URL of the page." )
    views = forms.IntegerField( widget = forms.HiddenInput(), initial = 0 )

    class Meta:
    # Provide an association between the ModelForm and a model
        model = Page
    # What fields do we want to include in our form?
    # This way we don't need every field in the model present.
    # Some fields may allow NULL values; we may not want to include them. 
    # Here, we are hiding the foreign key.
    # we can either exclude the category field from the form,
        exclude = ('category',)
    # or specify the fields to include (don't include the category field). 
    #fields = ('title', 'url', 'views')
    def clean(self):
        cleaned_data = self.cleaned_data 
        url = cleaned_data.get('url')
    # If url is not empty and doesn't start with 'http://', # then prepend 'http://'.
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
        return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta: 
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm): 
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

tango_with_django_project/rango/views.py
from django.shortcuts import render
from django.http import HttpResponse
from rango.models import Category
from rango.models import Page
from rango.forms import CategoryForm
from django.shortcuts import redirect
from rango.forms import PageForm
from django.urls import reverse

# Create your views here.

def index(request):
# Query the database for a list of ALL categories currently stored.
# Order the categories by the number of likes in descending order.
# Retrieve the top 5 only -- or all if less than 5.
# Place the list in our context_dict dictionary (with our boldmessage!) # that will be passed to the template engine.
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('views')[:5]
    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list
    # Render the response and send it back!
    return render(request, 'rango/index.html', context=context_dict)


def about(request):
    return render(request, 'rango/about.html')

def show_category(request, category_name_slug):
    # Create a context dictionary which we can pass 
    # to the template rendering engine. 
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None
    return render(request, 'rango/category.html', context=context_dict)

def add_category(request): 
    form = CategoryForm()
    # A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        # Have we been provided with a valid form?
        if form.is_valid():
            # Save the new category to the database. 
            form.save(commit=True)
        # Now that the category is saved, we could confirm this.
        # For now, just redirect the user back to the index view. 
            return redirect(reverse('rango:index'))
        else:
            # The supplied form contained errors -
            # just print them to the terminal.
            print(form.errors)
            # Will handle the bad form, new form, or no form supplied cases. 
            # Render the form with error messages (if any).
    return render(request, 'rango/add_category.html', {'form': form})

def add_page(request, category_name_slug): 
    try:
        category = Category.objects.get(slug=category_name_slug) 
    except Category.DoesNotExist:
        category = None
    # You cannot add a page to a Category that does not exist...
    if category is None:
        return redirect(reverse('rango:index'))
    
    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid(): 
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
        else: 
            print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)

tango_with_django_project/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About Rango
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>
    <div>
        here is the about page.<br />
        <strong>This tutorial has been put together by Conor</strong><br />
        <p>Visits: {{ visits }}</p>
    </div>
    <div>

        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
        <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat." />

    </div>
{% endblock %}

tango_with_django_project/templates/rango/add_category.html
{% extends 'rango/base.html' %}

{% block title_block %}
    Add a Category
{% endblock %}   

{% block body_block %}
    {% if user.is_authenticated %}
    <h1>Add a Category</h1>
    <div>
        <form id = "category_form" method = "post" action = "/rango/add_category/">

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Create Category" />
        </form>
    </div>
    {% else %}
        <p>You need to be logged in to add a category. Please <a href="{% url 'rango:login' %}">login</a>.</p>
    {% endif %}
{% endblock %}

tango_with_django_project/templates/rango/add_page.html
{% extends 'rango/base.html' %}

{% block title_block %}
    Add a Page
{% endblock %}

{% block block_body %}
    <body>
        <h1>Add a Page</h1>
        <div>
            <form id="page_form" method="post" action="/rango/category/{{ category.slug }}/add_page/">
                
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                {% endfor %}

                <input type="submit" name="submit" value="Create Category">

            </form>
        </div>
    </body>
{% endblock %}

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %} 
<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>Rango - {% block title_block %}How to Tango with Django!{% endblock %}</title>
    </head>
    <body>
        <div>
            {% block body_block %} 
            {% endblock %}
        </div>

        <div>
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
                {% if user.is_authenticated %}
                        <!-- Show these links when the user is logged in -->
                    <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                    <li><a href="{% url 'rango:logout' %}">Logout</a></li> 
                    <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
                {% else %}
                        <!-- Show these links when the user is NOT logged in -->
                    <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
                    <li><a href="{% url 'rango:login' %}">Login</a></li> 
                {% endif %}
                        <!-- Outside the conditional statements, ALWAYS show -->
                    <li><a href="{% url 'rango:about' %}">About</a></li>
                    <li><a href="{% url 'rango:index' %}">Index</a></li>
            </ul>
        </div>
    </body> 
</html>

tango_with_django_project/templates/rango/categories.html
<ul>
    {% if categories %}
        {% for c in categories %}
            {% if c == current_category %}
            <li>
                <strong><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></strong>
            </li>
            {% else %}
            <li>
                <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
            </li>
            {% endif %}
        {% endfor %}
    {% endif %}
</ul>

tango_with_django_project/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
    <h1>{{ category.name }}</h1> 
    {% if pages %}
    <ul>
        {% for page in pages %}
        <li><a href="{{ page.url }}">{{ page.title }}</a></li> 
        {% endfor %}
    </ul>
    {% else %}
    <strong>No pages currently in category.</strong> 
    {% endif %}
    {% if user.is_authenticated %}
    <a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br /> 
    {% endif %}
    {% else %}
    The specified category does not exist.
    {% endif %}
{% endblock %}

tango_with_django_project/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Homepage
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>
    <div>
        {% if user.is_authenticated %}
            howdy {{ user.username }}!
        {% else %}
            hey there partner! 
        {% endif %}
        <br/> 
        <strong>{{ boldmessage }}</strong><br />
    </div>

    <h2>Most favored categories</h2>
    {% if categories %}
        <ul>
        {% for category in categories %}
            <li>
                <a href="/rango/category/{{ category.slug }}/">{{ category.name }}</a>
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <strong>There are no categories present.</strong> 
    {% endif %}

    <h2>Most viewed pages</h2>
    {% if pages %}
        <div>
            <u1>
                {% for page in pages %}
                    <li>
                        <a href = "{{page.url}}">{{ page.title }}</a> - {{ page.views }} views
                    </li>
                {% endfor %}
            </u1>
            </div>
        {% else %}
            <div>
                <strong>There are no pages present.</strong>
            </div>
        {% endif %}
        
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
{% endblock %}

tango_with_django_project/templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}
{% block body_block %}
<h1>Login to Rango</h1>
<form id="login_form" method="post" action="{% url 'rango:login' %}">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50" />
    <br />
    Password: <input type="password" name="password" value="" size="50" /> 
    <br />
    <input type="submit" value="submit" />
</form>
{% endblock %}

tango_with_django_project/templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
<h1>Register for Rango</h1>
{% if registered %}
Rango says: <strong>thank you for registering!</strong>
<a href="/rango/">Return to the homepage.</a>
{% else %}
Rango says: <strong>register here!</strong><br />
<form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">

    {% csrf_token %}

    <!-- Display each form  -->
    {{ user_form.as_p }}
    {{ profile_form.as_p }}

    <!-- Provide a button to click to submit the form. -->
    <input type="submit" name="submit" value="Register" /> 
</form>
{% endif %}
{% endblock %}

tango_with_django_project/templates/rango/restricted.html
{% extends 'rango/base.html' %}

{% block title_block %}Restricted Page{% endblock %}

{% block body_block %}
    <h2>Since you're logged in, you can see this text!</h2>
{% endblock %}